/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as ManualPericiaRouteImport } from './routes/manual-pericia'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IaDebugRouteImport } from './routes/ia-debug'
import { Route as GuiaRecursoRouteImport } from './routes/guia-recurso'
import { Route as GuiaAuxilioRouteImport } from './routes/guia-auxilio'
import { Route as GuiaAposentadoriaRouteImport } from './routes/guia-aposentadoria'
import { Route as FunisRouteImport } from './routes/funis'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConstrutorRouteImport } from './routes/construtor'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapturaSlugRouteImport } from './routes/captura.$slug'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as ApiSimulateRouteImport } from './routes/api/simulate'
import { Route as ApiMediaProxyRouteImport } from './routes/api/media-proxy'
import { Route as ApiLeadMagnetUploadRouteImport } from './routes/api/lead-magnet-upload'
import { Route as ApiGeneratePromptRouteImport } from './routes/api/generate-prompt'
import { Route as ApiContentGenerateRouteImport } from './routes/api/content-generate'
import { Route as ApiDiagnosticoRouteImport } from './routes/api/diagnostico'
import { Route as ApiDebugWebhookRouteImport } from './routes/api/debug-webhook'
import { Route as ApiPublicZapsignWebhookRouteImport } from './routes/api/public/zapsign-webhook'
import { Route as ApiPublicWorkflowTickRouteImport } from './routes/api/public/workflow-tick'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicInstagramLeadRouteImport } from './routes/api/public/instagram-lead'
import { Route as ApiPublicInstagramFollowupTickRouteImport } from './routes/api/public/instagram-followup-tick'
import { Route as ApiPublicCronScheduledRouteImport } from './routes/api/public/cron-scheduled'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron-reminders'
import { Route as ApiPublicCronReactivationRouteImport } from './routes/api/public/cron-reactivation'
import { Route as ApiPublicCronPostConsultaRouteImport } from './routes/api/public/cron-post-consulta'
import { Route as ApiPublicCronDatajudRouteImport } from './routes/api/public/cron-datajud'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualPericiaRoute = ManualPericiaRouteImport.update({
  id: '/manual-pericia',
  path: '/manual-pericia',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IaDebugRoute = IaDebugRouteImport.update({
  id: '/ia-debug',
  path: '/ia-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRecursoRoute = GuiaRecursoRouteImport.update({
  id: '/guia-recurso',
  path: '/guia-recurso',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaAuxilioRoute = GuiaAuxilioRouteImport.update({
  id: '/guia-auxilio',
  path: '/guia-auxilio',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaAposentadoriaRoute = GuiaAposentadoriaRouteImport.update({
  id: '/guia-aposentadoria',
  path: '/guia-aposentadoria',
  getParentRoute: () => rootRouteImport,
} as any)
const FunisRoute = FunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstrutorRoute = ConstrutorRouteImport.update({
  id: '/construtor',
  path: '/construtor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaSlugRoute = CapturaSlugRouteImport.update({
  id: '/captura/$slug',
  path: '/captura/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowsRoute,
} as any)
const ApiSimulateRoute = ApiSimulateRouteImport.update({
  id: '/api/simulate',
  path: '/api/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaProxyRoute = ApiMediaProxyRouteImport.update({
  id: '/api/media-proxy',
  path: '/api/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadMagnetUploadRoute = ApiLeadMagnetUploadRouteImport.update({
  id: '/api/lead-magnet-upload',
  path: '/api/lead-magnet-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePromptRoute = ApiGeneratePromptRouteImport.update({
  id: '/api/generate-prompt',
  path: '/api/generate-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentGenerateRoute = ApiContentGenerateRouteImport.update({
  id: '/api/content-generate',
  path: '/api/content-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticoRoute = ApiDiagnosticoRouteImport.update({
  id: '/api/diagnostico',
  path: '/api/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugWebhookRoute = ApiDebugWebhookRouteImport.update({
  id: '/api/debug-webhook',
  path: '/api/debug-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZapsignWebhookRoute = ApiPublicZapsignWebhookRouteImport.update({
  id: '/api/public/zapsign-webhook',
  path: '/api/public/zapsign-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkflowTickRoute = ApiPublicWorkflowTickRouteImport.update({
  id: '/api/public/workflow-tick',
  path: '/api/public/workflow-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramLeadRoute =
  ApiPublicInstagramLeadRouteImport.update({
    id: '/api/public/instagram-lead',
    path: '/api/public/instagram-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramFollowupTickRoute =
  ApiPublicInstagramFollowupTickRouteImport.update({
    id: '/api/public/instagram-followup-tick',
    path: '/api/public/instagram-followup-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScheduledRoute = ApiPublicCronScheduledRouteImport.update({
  id: '/api/public/cron-scheduled',
  path: '/api/public/cron-scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron-reminders',
  path: '/api/public/cron-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronReactivationRoute =
  ApiPublicCronReactivationRouteImport.update({
    id: '/api/public/cron-reactivation',
    path: '/api/public/cron-reactivation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPostConsultaRoute =
  ApiPublicCronPostConsultaRouteImport.update({
    id: '/api/public/cron-post-consulta',
    path: '/api/public/cron-post-consulta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDatajudRoute = ApiPublicCronDatajudRouteImport.update({
  id: '/api/public/cron-datajud',
  path: '/api/public/cron-datajud',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/conteudo': typeof ConteudoRoute
  '/construtor': typeof ConstrutorRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/funis': typeof FunisRoute
  '/guia-aposentadoria': typeof GuiaAposentadoriaRoute
  '/guia-auxilio': typeof GuiaAuxilioRoute
  '/guia-recurso': typeof GuiaRecursoRoute
  '/ia-debug': typeof IaDebugRoute
  '/inbox': typeof InboxRoute
  '/instagram': typeof InstagramRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/manual-pericia': typeof ManualPericiaRoute
  '/manual': typeof ManualRoute
  '/processos': typeof ProcessosRoute
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRoute
  '/whatsapp': typeof WhatsappRoute
  '/wizard': typeof WizardRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/debug-webhook': typeof ApiDebugWebhookRoute
  '/api/content-generate': typeof ApiContentGenerateRoute
  '/api/diagnostico': typeof ApiDiagnosticoRoute
  '/api/generate-prompt': typeof ApiGeneratePromptRoute
  '/api/lead-magnet-upload': typeof ApiLeadMagnetUploadRoute
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/simulate': typeof ApiSimulateRoute
  '/captura/$slug': typeof CapturaSlugRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/api/public/cron-datajud': typeof ApiPublicCronDatajudRoute
  '/api/public/cron-post-consulta': typeof ApiPublicCronPostConsultaRoute
  '/api/public/cron-reactivation': typeof ApiPublicCronReactivationRoute
  '/api/public/cron-reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/cron-scheduled': typeof ApiPublicCronScheduledRoute
  '/api/public/instagram-followup-tick': typeof ApiPublicInstagramFollowupTickRoute
  '/api/public/instagram-lead': typeof ApiPublicInstagramLeadRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/workflow-tick': typeof ApiPublicWorkflowTickRoute
  '/api/public/zapsign-webhook': typeof ApiPublicZapsignWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/conteudo': typeof ConteudoRoute
  '/construtor': typeof ConstrutorRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/funis': typeof FunisRoute
  '/guia-aposentadoria': typeof GuiaAposentadoriaRoute
  '/guia-auxilio': typeof GuiaAuxilioRoute
  '/guia-recurso': typeof GuiaRecursoRoute
  '/ia-debug': typeof IaDebugRoute
  '/inbox': typeof InboxRoute
  '/instagram': typeof InstagramRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/manual-pericia': typeof ManualPericiaRoute
  '/manual': typeof ManualRoute
  '/processos': typeof ProcessosRoute
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRoute
  '/whatsapp': typeof WhatsappRoute
  '/wizard': typeof WizardRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/debug-webhook': typeof ApiDebugWebhookRoute
  '/api/content-generate': typeof ApiContentGenerateRoute
  '/api/diagnostico': typeof ApiDiagnosticoRoute
  '/api/generate-prompt': typeof ApiGeneratePromptRoute
  '/api/lead-magnet-upload': typeof ApiLeadMagnetUploadRoute
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/simulate': typeof ApiSimulateRoute
  '/captura/$slug': typeof CapturaSlugRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/api/public/cron-datajud': typeof ApiPublicCronDatajudRoute
  '/api/public/cron-post-consulta': typeof ApiPublicCronPostConsultaRoute
  '/api/public/cron-reactivation': typeof ApiPublicCronReactivationRoute
  '/api/public/cron-reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/cron-scheduled': typeof ApiPublicCronScheduledRoute
  '/api/public/instagram-followup-tick': typeof ApiPublicInstagramFollowupTickRoute
  '/api/public/instagram-lead': typeof ApiPublicInstagramLeadRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/workflow-tick': typeof ApiPublicWorkflowTickRoute
  '/api/public/zapsign-webhook': typeof ApiPublicZapsignWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/conteudo': typeof ConteudoRoute
  '/construtor': typeof ConstrutorRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/funis': typeof FunisRoute
  '/guia-aposentadoria': typeof GuiaAposentadoriaRoute
  '/guia-auxilio': typeof GuiaAuxilioRoute
  '/guia-recurso': typeof GuiaRecursoRoute
  '/ia-debug': typeof IaDebugRoute
  '/inbox': typeof InboxRoute
  '/instagram': typeof InstagramRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/manual-pericia': typeof ManualPericiaRoute
  '/manual': typeof ManualRoute
  '/processos': typeof ProcessosRoute
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRoute
  '/whatsapp': typeof WhatsappRoute
  '/wizard': typeof WizardRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/debug-webhook': typeof ApiDebugWebhookRoute
  '/api/content-generate': typeof ApiContentGenerateRoute
  '/api/diagnostico': typeof ApiDiagnosticoRoute
  '/api/generate-prompt': typeof ApiGeneratePromptRoute
  '/api/lead-magnet-upload': typeof ApiLeadMagnetUploadRoute
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/simulate': typeof ApiSimulateRoute
  '/captura/$slug': typeof CapturaSlugRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/api/public/cron-datajud': typeof ApiPublicCronDatajudRoute
  '/api/public/cron-post-consulta': typeof ApiPublicCronPostConsultaRoute
  '/api/public/cron-reactivation': typeof ApiPublicCronReactivationRoute
  '/api/public/cron-reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/cron-scheduled': typeof ApiPublicCronScheduledRoute
  '/api/public/instagram-followup-tick': typeof ApiPublicInstagramFollowupTickRoute
  '/api/public/instagram-lead': typeof ApiPublicInstagramLeadRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/workflow-tick': typeof ApiPublicWorkflowTickRoute
  '/api/public/zapsign-webhook': typeof ApiPublicZapsignWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/clientes'
    | '/configuracoes'
    | '/conhecimento'
    | '/conteudo'
    | '/construtor'
    | '/contratos'
    | '/dashboard'
    | '/diagnostico'
    | '/funis'
    | '/guia-aposentadoria'
    | '/guia-auxilio'
    | '/guia-recurso'
    | '/ia-debug'
    | '/inbox'
    | '/instagram'
    | '/kanban'
    | '/login'
    | '/manual-pericia'
    | '/manual'
    | '/processos'
    | '/relatorios'
    | '/templates'
    | '/whatsapp'
    | '/wizard'
    | '/workflows'
    | '/api/debug-webhook'
    | '/api/content-generate'
    | '/api/diagnostico'
    | '/api/generate-prompt'
    | '/api/lead-magnet-upload'
    | '/api/media-proxy'
    | '/api/simulate'
    | '/captura/$slug'
    | '/workflows/$id'
    | '/api/public/cron-datajud'
    | '/api/public/cron-post-consulta'
    | '/api/public/cron-reactivation'
    | '/api/public/cron-reminders'
    | '/api/public/cron-scheduled'
    | '/api/public/instagram-followup-tick'
    | '/api/public/instagram-lead'
    | '/api/public/whatsapp-webhook'
    | '/api/public/workflow-tick'
    | '/api/public/zapsign-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/clientes'
    | '/configuracoes'
    | '/conhecimento'
    | '/conteudo'
    | '/construtor'
    | '/contratos'
    | '/dashboard'
    | '/diagnostico'
    | '/funis'
    | '/guia-aposentadoria'
    | '/guia-auxilio'
    | '/guia-recurso'
    | '/ia-debug'
    | '/inbox'
    | '/instagram'
    | '/kanban'
    | '/login'
    | '/manual-pericia'
    | '/manual'
    | '/processos'
    | '/relatorios'
    | '/templates'
    | '/whatsapp'
    | '/wizard'
    | '/workflows'
    | '/api/debug-webhook'
    | '/api/content-generate'
    | '/api/diagnostico'
    | '/api/generate-prompt'
    | '/api/lead-magnet-upload'
    | '/api/media-proxy'
    | '/api/simulate'
    | '/captura/$slug'
    | '/workflows/$id'
    | '/api/public/cron-datajud'
    | '/api/public/cron-post-consulta'
    | '/api/public/cron-reactivation'
    | '/api/public/cron-reminders'
    | '/api/public/cron-scheduled'
    | '/api/public/instagram-followup-tick'
    | '/api/public/instagram-lead'
    | '/api/public/whatsapp-webhook'
    | '/api/public/workflow-tick'
    | '/api/public/zapsign-webhook'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/clientes'
    | '/configuracoes'
    | '/conhecimento'
    | '/conteudo'
    | '/construtor'
    | '/contratos'
    | '/dashboard'
    | '/diagnostico'
    | '/funis'
    | '/guia-aposentadoria'
    | '/guia-auxilio'
    | '/guia-recurso'
    | '/ia-debug'
    | '/inbox'
    | '/instagram'
    | '/kanban'
    | '/login'
    | '/manual-pericia'
    | '/manual'
    | '/processos'
    | '/relatorios'
    | '/templates'
    | '/whatsapp'
    | '/wizard'
    | '/workflows'
    | '/api/debug-webhook'
    | '/api/content-generate'
    | '/api/diagnostico'
    | '/api/generate-prompt'
    | '/api/lead-magnet-upload'
    | '/api/media-proxy'
    | '/api/simulate'
    | '/captura/$slug'
    | '/workflows/$id'
    | '/api/public/cron-datajud'
    | '/api/public/cron-post-consulta'
    | '/api/public/cron-reactivation'
    | '/api/public/cron-reminders'
    | '/api/public/cron-scheduled'
    | '/api/public/instagram-followup-tick'
    | '/api/public/instagram-lead'
    | '/api/public/whatsapp-webhook'
    | '/api/public/workflow-tick'
    | '/api/public/zapsign-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  ConteudoRoute: typeof ConteudoRoute
  ConstrutorRoute: typeof ConstrutorRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  FunisRoute: typeof FunisRoute
  GuiaAposentadoriaRoute: typeof GuiaAposentadoriaRoute
  GuiaAuxilioRoute: typeof GuiaAuxilioRoute
  GuiaRecursoRoute: typeof GuiaRecursoRoute
  IaDebugRoute: typeof IaDebugRoute
  InboxRoute: typeof InboxRoute
  InstagramRoute: typeof InstagramRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  ManualPericiaRoute: typeof ManualPericiaRoute
  ManualRoute: typeof ManualRoute
  ProcessosRoute: typeof ProcessosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TemplatesRoute: typeof TemplatesRoute
  WhatsappRoute: typeof WhatsappRoute
  WizardRoute: typeof WizardRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ApiDebugWebhookRoute: typeof ApiDebugWebhookRoute
  ApiContentGenerateRoute: typeof ApiContentGenerateRoute
  ApiDiagnosticoRoute: typeof ApiDiagnosticoRoute
  ApiGeneratePromptRoute: typeof ApiGeneratePromptRoute
  ApiLeadMagnetUploadRoute: typeof ApiLeadMagnetUploadRoute
  ApiMediaProxyRoute: typeof ApiMediaProxyRoute
  ApiSimulateRoute: typeof ApiSimulateRoute
  CapturaSlugRoute: typeof CapturaSlugRoute
  ApiPublicCronDatajudRoute: typeof ApiPublicCronDatajudRoute
  ApiPublicCronPostConsultaRoute: typeof ApiPublicCronPostConsultaRoute
  ApiPublicCronReactivationRoute: typeof ApiPublicCronReactivationRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicCronScheduledRoute: typeof ApiPublicCronScheduledRoute
  ApiPublicInstagramFollowupTickRoute: typeof ApiPublicInstagramFollowupTickRoute
  ApiPublicInstagramLeadRoute: typeof ApiPublicInstagramLeadRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicWorkflowTickRoute: typeof ApiPublicWorkflowTickRoute
  ApiPublicZapsignWebhookRoute: typeof ApiPublicZapsignWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-pericia': {
      id: '/manual-pericia'
      path: '/manual-pericia'
      fullPath: '/manual-pericia'
      preLoaderRoute: typeof ManualPericiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-debug': {
      id: '/ia-debug'
      path: '/ia-debug'
      fullPath: '/ia-debug'
      preLoaderRoute: typeof IaDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-recurso': {
      id: '/guia-recurso'
      path: '/guia-recurso'
      fullPath: '/guia-recurso'
      preLoaderRoute: typeof GuiaRecursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-auxilio': {
      id: '/guia-auxilio'
      path: '/guia-auxilio'
      fullPath: '/guia-auxilio'
      preLoaderRoute: typeof GuiaAuxilioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-aposentadoria': {
      id: '/guia-aposentadoria'
      path: '/guia-aposentadoria'
      fullPath: '/guia-aposentadoria'
      preLoaderRoute: typeof GuiaAposentadoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funis': {
      id: '/funis'
      path: '/funis'
      fullPath: '/funis'
      preLoaderRoute: typeof FunisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construtor': {
      id: '/construtor'
      path: '/construtor'
      fullPath: '/construtor'
      preLoaderRoute: typeof ConstrutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/api/simulate': {
      id: '/api/simulate'
      path: '/api/simulate'
      fullPath: '/api/simulate'
      preLoaderRoute: typeof ApiSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura/$slug': {
      id: '/captura/$slug'
      path: '/captura/$slug'
      fullPath: '/captura/$slug'
      preLoaderRoute: typeof CapturaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-proxy': {
      id: '/api/media-proxy'
      path: '/api/media-proxy'
      fullPath: '/api/media-proxy'
      preLoaderRoute: typeof ApiMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-prompt': {
      id: '/api/generate-prompt'
      path: '/api/generate-prompt'
      fullPath: '/api/generate-prompt'
      preLoaderRoute: typeof ApiGeneratePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-generate': {
      id: '/api/content-generate'
      path: '/api/content-generate'
      fullPath: '/api/content-generate'
      preLoaderRoute: typeof ApiContentGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-magnet-upload': {
      id: '/api/lead-magnet-upload'
      path: '/api/lead-magnet-upload'
      fullPath: '/api/lead-magnet-upload'
      preLoaderRoute: typeof ApiLeadMagnetUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostico': {
      id: '/api/diagnostico'
      path: '/api/diagnostico'
      fullPath: '/api/diagnostico'
      preLoaderRoute: typeof ApiDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-webhook': {
      id: '/api/debug-webhook'
      path: '/api/debug-webhook'
      fullPath: '/api/debug-webhook'
      preLoaderRoute: typeof ApiDebugWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapsign-webhook': {
      id: '/api/public/zapsign-webhook'
      path: '/api/public/zapsign-webhook'
      fullPath: '/api/public/zapsign-webhook'
      preLoaderRoute: typeof ApiPublicZapsignWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workflow-tick': {
      id: '/api/public/workflow-tick'
      path: '/api/public/workflow-tick'
      fullPath: '/api/public/workflow-tick'
      preLoaderRoute: typeof ApiPublicWorkflowTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-lead': {
      id: '/api/public/instagram-lead'
      path: '/api/public/instagram-lead'
      fullPath: '/api/public/instagram-lead'
      preLoaderRoute: typeof ApiPublicInstagramLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-followup-tick': {
      id: '/api/public/instagram-followup-tick'
      path: '/api/public/instagram-followup-tick'
      fullPath: '/api/public/instagram-followup-tick'
      preLoaderRoute: typeof ApiPublicInstagramFollowupTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-scheduled': {
      id: '/api/public/cron-scheduled'
      path: '/api/public/cron-scheduled'
      fullPath: '/api/public/cron-scheduled'
      preLoaderRoute: typeof ApiPublicCronScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-reminders': {
      id: '/api/public/cron-reminders'
      path: '/api/public/cron-reminders'
      fullPath: '/api/public/cron-reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-reactivation': {
      id: '/api/public/cron-reactivation'
      path: '/api/public/cron-reactivation'
      fullPath: '/api/public/cron-reactivation'
      preLoaderRoute: typeof ApiPublicCronReactivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-post-consulta': {
      id: '/api/public/cron-post-consulta'
      path: '/api/public/cron-post-consulta'
      fullPath: '/api/public/cron-post-consulta'
      preLoaderRoute: typeof ApiPublicCronPostConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-datajud': {
      id: '/api/public/cron-datajud'
      path: '/api/public/cron-datajud'
      fullPath: '/api/public/cron-datajud'
      preLoaderRoute: typeof ApiPublicCronDatajudRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkflowsRouteChildren {
  WorkflowsIdRoute: typeof WorkflowsIdRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsIdRoute: WorkflowsIdRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  ConteudoRoute: ConteudoRoute,
  ConstrutorRoute: ConstrutorRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  FunisRoute: FunisRoute,
  GuiaAposentadoriaRoute: GuiaAposentadoriaRoute,
  GuiaAuxilioRoute: GuiaAuxilioRoute,
  GuiaRecursoRoute: GuiaRecursoRoute,
  IaDebugRoute: IaDebugRoute,
  InboxRoute: InboxRoute,
  InstagramRoute: InstagramRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  ManualPericiaRoute: ManualPericiaRoute,
  ManualRoute: ManualRoute,
  ProcessosRoute: ProcessosRoute,
  RelatoriosRoute: RelatoriosRoute,
  TemplatesRoute: TemplatesRoute,
  WhatsappRoute: WhatsappRoute,
  WizardRoute: WizardRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ApiDebugWebhookRoute: ApiDebugWebhookRoute,
  ApiContentGenerateRoute: ApiContentGenerateRoute,
  ApiDiagnosticoRoute: ApiDiagnosticoRoute,
  ApiGeneratePromptRoute: ApiGeneratePromptRoute,
  ApiLeadMagnetUploadRoute: ApiLeadMagnetUploadRoute,
  ApiMediaProxyRoute: ApiMediaProxyRoute,
  ApiSimulateRoute: ApiSimulateRoute,
  CapturaSlugRoute: CapturaSlugRoute,
  ApiPublicCronDatajudRoute: ApiPublicCronDatajudRoute,
  ApiPublicCronPostConsultaRoute: ApiPublicCronPostConsultaRoute,
  ApiPublicCronReactivationRoute: ApiPublicCronReactivationRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicCronScheduledRoute: ApiPublicCronScheduledRoute,
  ApiPublicInstagramFollowupTickRoute: ApiPublicInstagramFollowupTickRoute,
  ApiPublicInstagramLeadRoute: ApiPublicInstagramLeadRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicWorkflowTickRoute: ApiPublicWorkflowTickRoute,
  ApiPublicZapsignWebhookRoute: ApiPublicZapsignWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
